# Generated by Django 4.2.7 on 2026-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientexchangeaccount_locked_initial_final_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='cycle_start_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when current PnL cycle started. Used to filter settlements by cycle.', null=True),
        ),
    ]
