# Generated by Django 4.2.7 on 2026-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cycle_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='locked_initial_funding',
            field=models.BigIntegerField(blank=True, help_text='Funding amount when share was locked. Used to detect funding changes that should reset cycle.', null=True),
        ),
    ]
