# Generated by Django 4.2.7 on 2025-12-17 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientdailybalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdailybalance',
            options={'ordering': ['-date', 'client_exchange__exchange__name'], 'verbose_name_plural': 'Client Daily Balances'},
        ),
        migrations.AlterUniqueTogether(
            name='clientdailybalance',
            unique_together={('client', 'date')},
        ),
        migrations.AddField(
            model_name='clientdailybalance',
            name='client_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='core.clientexchange'),
        ),
        migrations.AlterField(
            model_name='clientdailybalance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances_legacy', to='core.client'),
        ),
        migrations.AlterField(
            model_name='clientdailybalance',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, help_text="Remaining balance in client's account for this exchange", max_digits=14),
        ),
        migrations.AlterUniqueTogether(
            name='clientdailybalance',
            unique_together={('client_exchange', 'date'), ('client', 'date')},
        ),
    ]
