# Generated by Django 4.2.7 on 2025-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_clientdailybalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Admin loss percentage when client is in profit (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=11.0, help_text='Admin profit percentage when client is in loss (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_share_on_admin_loss_pct',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Company share percentage from admin loss (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_share_on_admin_profit_pct',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Company share percentage from admin profit (%)', max_digits=5),
        ),
    ]
