# Generated by Django 4.2.7 on 2025-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_profit_loss_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='admin_loss_percentage',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='admin_profit_percentage',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_share_on_admin_loss_pct',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_share_on_admin_profit_pct',
        ),
        migrations.AddField(
            model_name='clientdailybalance',
            name='extra_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra money adjustment if exchange balance is low (positive amount)', max_digits=14),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_loss_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Admin loss percentage on client profit (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_profit_pct',
            field=models.DecimalField(decimal_places=2, default=11.0, help_text='Admin profit percentage on client loss (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_share_on_loss_pct',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Company share percentage from admin loss (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_share_on_profit_pct',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Company share percentage from admin profit (%)', max_digits=5),
        ),
    ]
