# Generated by Django 4.2.7 on 2025-12-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_systemsettings_admin_loss_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total pending amount (unpaid losses) for this client-exchange', max_digits=14)),
                ('note', models.TextField(blank=True, help_text='Optional note about pending amount')),
                ('client_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_amounts', to='core.clientexchange')),
            ],
            options={
                'verbose_name_plural': 'Pending Amounts',
                'unique_together': {('client_exchange',)},
            },
        ),
    ]
