# Generated by Django 4.2.7 on 2025-12-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pendingamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Name of person who referred this client', max_length=255, null=True),
        ),
    ]
