# Generated by Django 4.2.7 on 2025-12-21 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_remove_systemsettings_admin_loss_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Client code (unique per user)', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'code')},
        ),
    ]
