# Generated by Django 4.2.7 on 2025-12-27 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_tally_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexchange',
            name='balance_last_updated',
            field=models.DateTimeField(blank=True, help_text='Timestamp when cached balance fields were last updated', null=True),
        ),
        migrations.AddField(
            model_name='clientexchange',
            name='cached_current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cached current exchange balance (updated automatically)', max_digits=14),
        ),
        migrations.AddField(
            model_name='clientexchange',
            name='cached_old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cached old balance after last settlement (updated automatically)', max_digits=14),
        ),
        migrations.AddField(
            model_name='clientexchange',
            name='cached_total_funding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cached total funding amount (updated automatically)', max_digits=14),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'is_active'], name='core_client_user_id_bbc8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'is_company_client'], name='core_client_user_id_348836_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_company_client', 'is_active'], name='core_client_is_comp_df7ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code'], name='core_client_code_acc390_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdailybalance',
            index=models.Index(fields=['client_exchange', 'date'], name='core_client_client__652a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdailybalance',
            index=models.Index(fields=['client', 'date'], name='core_client_client__1398e6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdailybalance',
            index=models.Index(fields=['date'], name='core_client_date_1f47f7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientexchange',
            index=models.Index(fields=['client', 'is_active'], name='core_client_client__7ef57c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientexchange',
            index=models.Index(fields=['exchange', 'is_active'], name='core_client_exchang_6493a9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientexchange',
            index=models.Index(fields=['is_active'], name='core_client_is_acti_75f94d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybalancesnapshot',
            index=models.Index(fields=['client_exchange', 'date'], name='core_dailyb_client__37c483_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybalancesnapshot',
            index=models.Index(fields=['date'], name='core_dailyb_date_e3d845_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client_exchange', 'transaction_type'], name='core_transa_client__5cf8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client_exchange', 'date'], name='core_transa_client__76b401_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'date'], name='core_transa_transac_3a4305_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='core_transa_date_2d33ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client_exchange', 'transaction_type', 'date'], name='core_transa_client__d6ab14_idx'),
        ),
    ]
