# Generated by Django 4.2.7 on 2025-12-28 05:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_optimize_database_indexes_and_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='One-time security deposit paid by company client (only for company clients)', max_digits=14),
        ),
        migrations.AddField(
            model_name='client',
            name='security_deposit_paid_date',
            field=models.DateField(blank=True, help_text='Date when security deposit was paid (one-time payment)', null=True),
        ),
    ]
