# Generated by Django 4.2.7 on 2026-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_loss_snapshot_constraints'),
        ('core', '0022_add_loss_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='capital_closed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital closed by this settlement (for audit trail, only for SETTLEMENT transactions)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='losssnapshot',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='True when loss is fully settled (remaining_loss = 0)'),
        ),
        migrations.AlterField(
            model_name='losssnapshot',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, help_text='ORIGINAL frozen loss amount - IMMUTABLE, NEVER changed after creation', max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='losssnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_settled', False)), fields=('client_exchange',), name='one_active_loss_per_exchange'),
        ),
    ]
