# Generated by Django 4.2.7 on 2026-01-05 15:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_loss_snapshot_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_amount', models.DecimalField(decimal_places=2, help_text='Frozen loss amount - NEVER recalculated, only reduced by SETTLEMENT', max_digits=14)),
                ('my_share_pct', models.DecimalField(decimal_places=2, help_text='Frozen my share percentage at loss creation time', max_digits=5)),
                ('company_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Frozen company share percentage at loss creation time', max_digits=5)),
                ('is_settled', models.BooleanField(default=False, help_text='True when loss is fully settled (loss_amount = 0)')),
                ('note', models.TextField(blank=True, help_text='Optional note about this loss snapshot')),
                ('balance_record', models.ForeignKey(help_text='Frozen balance record at time of loss creation (CB is frozen)', on_delete=django.db.models.deletion.PROTECT, related_name='loss_snapshots', to='core.clientdailybalance')),
                ('client_exchange', models.ForeignKey(help_text='Client-exchange combination this loss snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='loss_snapshots', to='core.clientexchange')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_exchange', 'is_settled'], name='core_losssn_client__346806_idx'), models.Index(fields=['is_settled'], name='core_losssn_is_sett_512e65_idx')],
            },
        ),
    ]
