# Generated by Django 4.2.7 on 2026-01-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_company_client_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingAmount',
        ),
    ]
